### ISSUE TITLE
Page "View" (not Edit) information alignment/density

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#168]
Would like to see the page information for viewing more dense, and field title/value aligned on the following screens:
- [ ] Site (alignment and spacing)
- [ ] Datum Location (alignment and spacing)
- [ ] Sensor (alignment)
- [ ] HWM (alignment and spacing)
- [ ] File (alignment and spacing)

**Comment by HansVraga** [comment]
@troddick was going to take a look, but may pass this to @mitchas as well

**Comment by troddick** [comment]
I'm working on this. It's in the logic on the details vs edit content within the pages. Shouldn't take me too long.

**Comment by troddick** [comment]
site and datum location fixed so far.

**Comment by troddick** [comment]
all done
