### ISSUE TITLE
Need loading indicator on Site Map for long event queries

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#170]
(from my testing) Switching to Sandy on the site map page takes some time, and without a loading indicator it can be misleading (the user may think nothing happened). Also, if the delay is enough, you can switch to sandy, then switch to another event, have that other event's sites load, and then have Sandy come back and load - which will leave you with a map of Sandy sites and the event set to not Sandy.

**Comment by HansVraga** [comment]
Multiple ways to indicate the map is waiting for loading. I know a universal 'loading' function is underway for the application - but first I think we consider a loading animation on the map itself.

**Comment by BlakeDraper** [comment]
Oh yes, we have this already. I've committed that functionality - just hasn't made it to the live test app yet.

And just to be clear - when we talk about a 'universal' loading spinner, what I am aiming for is a thing that can be used piece-wise - like for the map part or any other subsection of a page that may need it

**Comment by BlakeDraper** [comment]
Done.
