### ISSUE TITLE
What is Bootstrap 3.1.1 css doing in the app?

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/STNWeb#176]
I noticed we have a copy of bootstrap v3.1.1 included in the '/src/css' folder which means it is getting injected into the index of the app.

`<link rel="stylesheet" href="css/bootstrap_3.1.1.css">`

 @troddick I assume you included this explicitly for some reason. Do you remember why? I was curious what would happen if I removed it, and unfortunately this happened:

![bs3_1_1absent](https://cloud.githubusercontent.com/assets/6978380/14990254/5b1e95a4-1121-11e6-90b1-598587ff37b6.PNG)

You can see the Create dropdown is stuck in the out state. My cursor  was not near the Create button when I snapped that. I'd like to fix things so that the app works properly even without that included, as its bad form to have an outdated css package as a dependency. Maybe it just means taking whatever relevant class is in that file and transferring it to our custom css file. @mitchas would you take a look at this? When running the app off the gulp watch-dev server, just manually comment out the reference line on '/dev/index.html', reload page,  and you will see what I mean.

@troddick if you are aware of other reasons we needed the 3.1.1 that I didn't catch, let us know

**Comment by troddick** [comment]
I think a lot of stuff throughout the app is using the bootstrap 3.1.1 css. I'm using bootstrap classes throughout for the grid (ex: class="col-md-4"). I'm not sure what version the bootstrap.min.css file is referencing that I see when I right-click something that has the col-md.. class on it. It looks like both bootstrap 3.1.1 css and bootstrap.min.css are being referenced throughout

**Comment by BlakeDraper** [comment]
We have the full bootstrap package including css already included (3.3.6), so I'm asking if there is some reason we are specifically including this version on top of the other one? The grids are a core bootstrap thing so those don't go away.

**Comment by troddick** [comment]
No, no specific reason. Probably just was included when I first started and stuck around.

**Comment by BlakeDraper** [comment]
@mitchas is going to fix things so that the create thing behaves properly with 3.1.1 removed.
