### ISSUE TITLE
Login Screen intro text

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#194]
Right now...

![image](https://cloud.githubusercontent.com/assets/12058013/15127211/a33dc512-1603-11e6-9adf-53c3194ab249.png)

Bug Marie about what we want there.

**Comment by troddick** [comment]
The USGS Short-Term Network (STN) is a national-scale application and database designed to support USGS event-based sensor deployments and High-Water Mark (HWM) data collection efforts. The STN database is designed to encourage, but not require, repeated visits to temporary sensor deployment (wave or water level) or HWM locations. By developing a system that encourages repeated, as-needed deployments in the same locations, it facilitates the development of longer-term datasets of storm events than would be feasible by relying on field personnel's memories of previous deployments or interpretations of paper records alone. Such efficient, responses have become a cornerstone of the USGS Hazards Response.

You are logging into the data management system designed to submit, edit, and delete your information

Many PUBLIC ways to access flood event data:

Information on the program and the PUBLIC link to be distributed is: http://water.usgs.gov/floods/FEV/ 

View data from all events in the map viewer: https://stn.wim.usgs.gov/FEV

Download data by event, state, and more: http://stn.wim.usgs.gov/STNDataPortal/#

View the REST data services: http://stn.wim.usgs.gov/STNServices/Documentation.html

View the Map data services: http://stnmapservices.wim.usgs.gov:6080/arcgis/rest/services/STN

LOGIN BOXES HERE
For help please contact Marie blah blah blah

**Comment by troddick** [comment]
done
