### ISSUE TITLE
Switch out reverse Geocoder

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#198]
Remove Google's web api geocoder and use ESRI's reverse geocoder instead. No max daily limit.

https://developers.arcgis.com/rest/geocode/api-reference/geocoding-reverse-geocode.htm

**Comment by HansVraga** [comment]
Will need to find a solution that includes county.

**Comment by troddick** [comment]
Done. New reverse geocoder returns State and County only.
