### ISSUE TITLE
Site Map Enhancements

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#201]
Create greatly zoomed-in view of Site that includes the attached features that have lat/long information. Site Photos, HWMs and Objective Points. Make switching between this view and default view (that shows just the site and nearby sites) clear.

**Comment by HansVraga** [comment]
Named the zoomed-in site specific view: "Location Map"
Name the view for seeing nearby sites: "Nearby Sites"

**Comment by BlakeDraper** [comment]
> includes the attached features that have lat/long information. Sensor deploy points, HWMs and Objective Points. 

Do you mean graphically includes? Like shows those child elements on the map somehow?

**Comment by HansVraga** [comment]
Yes.

Hans Vraga
WiM Project Manager
12201 Sunrise Valley Dr. 5A118
Reston, VA 20192
office: 703-648-5670 cell: 571-524-1070

**Comment by BlakeDraper** [comment]
Did you all discuss a vision for this? I can go to the drawing board but right off the cuff I'm not picturing how we would show multiple (and in fact unlimited) features at the same point on the map. Also, can you clarify what 'sensor deploy points' refers to? The location of sensor deployment is by design the location of the site it belongs to.

**Comment by BlakeDraper** [comment]
Show specifically the photos, HWMs and OPs at their individual lat/long locations. This is practically probably not very useful because it assumes high accuracy of the lat/long significant figures. Will revisit when there is time in the future, but usefulness is dubious.

**Comment by HansVraga** [comment]
Adding on to what @BlakeDraper says above, will require example sites with quality enough data to even prototype such a view.

**Comment by HansVraga** [comment]
Adding on to this as the site map enhancements issue.
In regards to the detailed site map, there is site data in PA that _should_ have the required level of detail.
In regards to the "nearby sites" view, clicking on one of the nearby sites should give you a popup with the site number, and give you the option to navigate to that site.

**Comment by HansVraga** [comment]
From #317 - more on this. Request from Todd:

> Please add a method in STN for seeing HWMs on the map along with the site.  That's really important
