### ISSUE TITLE
dropdown cutoff within container

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#207]
This used to have a style applied that allowed for it to show the full dropdown on the outside of the container. It looks like .checkboxLayer.show has a position: absolute, which puts it inside the container and doesn't show the full thing.
![image](https://cloud.githubusercontent.com/assets/1580076/15551784/257083e6-227d-11e6-9b31-0a6b0a515f51.png)

**Comment by mitchas** [comment]
I had to do the position absolute to get it to show at all on smaller monitors. I thought I fixed this issue with the z-index but I guess not. I'll play around with it some more.
