### ISSUE TITLE
Some clarity to the Site Search

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#212]
Currently, performing a search then changing the event or navigating away and back without performing another search can be confusing. On one hand, it's handy to have your previous search results available to you if you navigate away, then back. On the other there is an expectation that changing one of your filters, and especially your event, should update the search, or at least clear it.

![image](https://cloud.githubusercontent.com/assets/12058013/15589825/7a24a418-2362-11e6-89f6-1620457555aa.png)

I propose we fix this by Adding a Title to the Search above the results (see image)  that includes all the filters set for the search. This way, it's more clear that the results below are from the last time "Search" was clicked.

**Comment by HansVraga** [comment]
So for example, that title could be Results for Event:Wilma (Date start: xxx, Date end: xxx, Network: xxx, etc.)

**Comment by lprivette** [comment]
Will be addressed in future refactor
