### ISSUE TITLE
Create site from searching

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#213]
(see image) Clicking 1 "Search" then 2 "Search" without changing filters opens the create site modal.

![image](https://cloud.githubusercontent.com/assets/12058013/15593965/1d65e648-237f-11e6-9c15-756f768f1cf8.png)

**Comment by troddick** [comment]
fixed.

**Comment by HansVraga** [comment]
This issue has cropped up again. Here is how I was able to recreate.

Step 0: From within STNWeb, refresh.
Step 1: Click Search
Step 2: Paste in a valid ID, such as MEFRA16026
Step 3: Click Search

New site create modal will open.

**Comment by HansVraga** [comment]
@troddick and I did some troubleshooting to recreate. We found a response being chopped up into an array?

**Comment by troddick** [comment]
Added accept json header and tested a bunch. Seems to have fixed it.
