### ISSUE TITLE
Site Create from Map - stray click freezes interface

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#220]
When creating a site from the map, once you click a spot on the map for the new site to get a dot, clicking on that dot brings up a never ending loading screen

![image](https://cloud.githubusercontent.com/assets/12058013/15614551/70760a1a-2407-11e6-9778-10a88a3bd8ff.png)

**Comment by BlakeDraper** [comment]
Note to self: this is because looking for siteid: newsite in the web services - failing, and never completes to turn off loading screen. Insert check.

**Comment by BlakeDraper** [comment]
Fixed with PR #224
