### ISSUE TITLE
Add show all sites view to map

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/STNWeb#222]
Need an option to show all sites, regardless of event or lack of event.

**Comment by HansVraga** [comment]
Some user stories for this:

> I love user stories!  And this one is pretty easy. Yes, there is an event-centric workflow, but the event starts will all possible sites as eligible for a deployment for that event. You skipped ahead a step in your logic: 
> 
> As a network planner (data chief), I need to be able to see where the sites are located and assign/direct field crews to groups of sites because I need to make sure that my field crews are efficient. 
> 
> As a field tech, I need to be able to see where to put the sensors for the sites that I am deploying for because I want to aim for sites that I have planned (either with or without a proposed sensor) and locations that have been deployed at before. These sites haven't been connected to an event yet, because that is my job! 
> 
> As a network planner (data chief), I want to be able to see all the locations that we have deployed at in the past or have brackets established because I need to identify both holes in the network coverage and areas with a nice network that overlap with possible collaborators (like a watershed association or national park area). 
> 
> As a national manager, I want to be able to see gaps in the network and highlight where we have brackets and proposed sensors or HWM only sites because I need to promote the network as a whole and direct internal communications to high or low performers in the network development. 
> 
> I could keep going but I think those are the three main users and why they all need this capability. I really like and think that cluster symbology would be perfect here and aim for something much more detailed than what I saw with one dot for each state in the great lakes.  Maybe something like a cluster for every state on load but quickly bounce down to a more detailed cluster per county level or something. 
> 
> Let me know if you need more.
> M

**Comment by BlakeDraper** [comment]
We now have a way for users to see non-event associated sites, but I am still preventing a show all sites option through a "at least one search parameter" rule. Let's see how this goes for now - may come up with a totally diferent, novel solution for the national manager story that needs to see literally all the STN sites at once.
