### ISSUE TITLE
Logout Timeout warning / redirect to log back in

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#227]
Upon submission of a form, Marie got logged out, presumably due to time-out. She didn't get redirected to the log-in screen, and had to manually click "Log Off" to get there and have a chance to log back in.

We should redirect a user to log back in if they've timed out.

**Comment by troddick** [comment]
I would need a little more information. 
Submitting a form, she got logged out, why presuming due to time-out? 
What form was she submitting? 
Was she in a modal?

**Comment by HansVraga** [comment]
We don't remember.
