### ISSUE TITLE
Date Validation in Site creation

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#231]
(from Greg P)
The validation did not catch when I made an "end date" before a "start date".  (Sorry can't remember names of the fields.)  This is just being nitpicky as no one should make this mistake but just in case I would validate the proper date chronology.

**Comment by troddick** [comment]
I'm guessing this is on the Data File create/edit pages. 
Added check on submit click that checks if end date is after start date (on all data file create/edit locations). If not, submit will stop and popup shows.
