### ISSUE TITLE
Map - Adjust filter to show sites not connected to an event

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#239]
This is to meet the minimal requirements for what is outlined in issue #222 - Adjust the filter and results on the map. 
- [x] Add a requirement for some filter rules to be set before filtering and showing sites
- [x] When a session event is set, change Event filter to read "Sites with [Event Name] data/instruments only?" and have a "YES / NO" toggle. 
- [x] When no session event set, hide Event filter option.

**Comment by BlakeDraper** [comment]
2/3 done with PR #240. Still need to impose minimum filter rule, and the no show when no session event.

**Comment by BlakeDraper** [comment]
Finished with PR #242
