### ISSUE TITLE
Approval Tab Improvements

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#275]
Recommended updates to the Approval Tab.
- [x] Text at top: "Search by one or more parameters to show your to-do lists for this event."
- [x] Add search by county.
Then 3 accordions 
- [x] 1: HWMs that need approval
     sortable table containing:
siteNo, elevation, height above grd, location descr, flagDate, bank, quality, type, stillwater, hwm_uncertainty, survey uncertainty, and a checkbox for approveIt.
      They can sort, and select (check box for each row) all hwms they want to approve and then click "approve selected HWMs" button.

- [x] 2. Data Files that need approval
     leave it as is for now until we do work on integrating scripts
- [x] 3. Peaks
    show list of site_no for this event that have some sort of data (hwms or sensor data files), but do not have a peak yet.

**Comment by troddick** [comment]
is this a good place to look and see if any datafiles are attached to any of these sites but not associated with a sensor?

**Comment by HansVraga** [comment]
Updated the Top comment from today's discussion.

**Comment by troddick** [comment]
I am almost done with #1 above, but I don't think I should go through with it and actually approve the hwms that are checked since we may be changing the way this is handled. As of now, I have the sortable table, checkboxes and an Approve button once some are checked, clicking it brings up an 'are you sure' modal, but doesn't actually complete the approval process.

**Comment by HansVraga** [comment]
Closing this issue as Approval is set to undergo an overhaul.
