### ISSUE TITLE
Filtering Events by State: Iowa has no events

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#276]
There is a 2007 Iowa flood event with sites - not sure why there are no events populated in the event select modal when you filter by state:Iowa.

![image](https://cloud.githubusercontent.com/assets/12058013/17854467/e6bfb130-6840-11e6-9540-8569e7975051.png)

**Comment by troddick** [comment]
fixed in stntest

**Comment by troddick** [comment]
done in production
