### ISSUE TITLE
event name check

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#285]
Add check on event name that it only contains letters and numbers (no other characters) before post/edit.

**Comment by troddick** [comment]
Done. (soon to be on stntest)
Only special characters allowed is - and _
otherwise, only numbers and letters.

**Comment by troddick** [comment]
live in stntest

**Comment by tkoenigusgs** [comment]
I think we still want to allow spaces, don't we?

**Comment by troddick** [comment]
good catch! I did not intend for spaces to be removed. I fixed it.
