### ISSUE TITLE
Add a mark for Public Fields In all forms

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#290]
Make it more obvious which fields are public information in the Quick HWM and Quick Sensor forms.
Suggestions include making the background of those fields shaded a different color, or adding a symbol in front of each public field.

**Comment by HansVraga** [comment]
Title update - we should make clear which fields are public (in FEV) on these forms.

**Comment by troddick** [comment]
Adding 'eye' with hover text 'Public field' next to all public information fields on the quick creates (hwm and sensor).
![image](https://cloud.githubusercontent.com/assets/1580076/21650237/ed6c1238-d269-11e6-887b-90e9a5ec5e2f.png)

Let me know if this is not the preferred way of making the fields clearly public, and I can change it.

**Comment by troddick** [comment]
Live in stntest

**Comment by tkoenigusgs** [comment]
dig it.
