### ISSUE TITLE
Group Quick HWM Survey Fields

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#291]
To make it move obvious a group of fields are specific to the Survey part of a HWM:
- [x] Move the "Tranquil/Stillwater" flag to below "Height above Ground"
- [x] Add _something_ (such as a small heading, block with different background color, or separator) to indicate the fields "Surveyed Date" through "Notes" are intended for the Survey task

**Comment by troddick** [comment]
Done in stntest

**Comment by tkoenigusgs** [comment]
Looks good in the Quick HWM modal, but for clarity and consistency, we should also do the same for the HWM and Edit HWM modals.
