### ISSUE TITLE
Field person sees "Add user" as an option

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#295]
I'm a field user, shouldn't see this:

![image](https://cloud.githubusercontent.com/assets/12058013/18451280/4477778a-7904-11e6-8b52-04d711c5ee62.png)

**Comment by troddick** [comment]
![image](https://cloud.githubusercontent.com/assets/1580076/21614138/dd8a0b94-d19d-11e6-87b0-ff9d726095e9.png)

**Comment by troddick** [comment]
Fixed in stntest

**Comment by troddick** [comment]
done in production
