### ISSUE TITLE
Add Coastal erosion layer

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/STNWeb#303]
> FEV is still the high priority but I forgot about this one:
> 
> Jamie Rhome from the NHC reminded me that they have new GIS products with their new inundation products. http://www.nhc.noaa.gov/refresh/graphics_at4+shtml/093327.shtml?inundation#contents
> 
> The GIS files are in a box below the map. Jamie's staff would be happy to work with you.

**Comment by BlakeDraper** [comment]
>Hello all,

We have made our coastal change probability forecasts for Matthew, as well as the beach morphology and modeled total water level data available through WMS here: http://olga.er.usgs.gov/stpgis/services/Vulnerability/real_time_storms/MapServer/WmsServer
Rest services are also available at: http://olga.er.usgs.gov/stpgis/rest/services/Vulnerability/real_time_storms/MapServer

Please let me know if you have any questions or trouble in adding this data on the storm mapper.

Thanks,
Heather

Heather Schreppel
IT Specialist (Data Management)
Cherokee Nation Technologies
contracted to U.S. Geological Survey
600 4th Street South
St. Petersburg, Florida  33701
Telephone:  727-502-8013
FAX:  727-502-8182 
hschreppel@usgs.gov

**Comment by lprivette** [comment]
data no longer available or at different location
