### ISSUE TITLE
Cannot delete/reselect networkname, or network type

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/STNWeb#305]
So far it seem to be an issue with angular resource delete not returning and issuing the followup delete request after the Options request
![capture](https://cloud.githubusercontent.com/assets/8713714/19165845/a27c0e10-8bc2-11e6-8c45-e811f97c1645.JPG)

I was able to successfully get the services to work directly using the unit tests and fiddler.

-------------------------related email below -------------------------------------------------
You found a good one here Russ - Jeremy and I will take a look.

Hans Vraga 
WiM Project Manager
703-648-5670
12201 Sunrise Valley Dr. 5A118 
MS 437
Reston, VA 20192

On Thu, Oct 6, 2016 at 8:15 AM, Lotspeich, Robert (Russ) rlotspei@usgs.gov wrote:
Sounds good Hans, thanks!

Here's another one...

I am trying to change this site, VAHAM07913, from an undefined network to SWaTH but it doesn't seem to like that. Could you look into that and let me know what you find?

Thanks,
Russ

R. Russell Lotspeich | Hydrologist | Surface Water Specialist
Office: 804.261.2637 | Mobile: 804.205.6685 | rlotspei@usgs.gov

U.S. Geological Survey | Virginia-West Virginia Water Science Center
1730 East Parham Road | Richmond, VA 23228 | http://va.water.usgs.gov

On Thu, Oct 6, 2016 at 8:03 AM, Vraga, Hans hvraga@usgs.gov wrote:
Russ,
If you click on the "?" next to that NWIS Connection heading, you'll see that you've already done what you need to have your RDG data show up in FEV.
Marie can elaborate more on this, but this section should really be completed after the event/during retrieval. 

(I didn't know this until I started looking into it myself).

Hans Vraga 
WiM Project Manager
703-648-5670
12201 Sunrise Valley Dr. 5A118 
MS 437
Reston, VA 20192

On Thu, Oct 6, 2016 at 7:48 AM, Lotspeich, Robert (Russ) rlotspei@usgs.gov wrote:
Good morning!

We have deployed an RDG in STN for VA (VAACC07831). I was looking over the deployment and started to complete the NWIS connection area. The problem is "Good data end time" is a required field but the RDG was just deployed yesterday and will likely run through next week. What is the intent of this form? I assumed it was the link between STN and NWIS. If so, the end time should not be required because we don't know it yet. Am I making any sense? I'm sure there is a reason it is required, but I wanted to bring it up in case it could be, or needed to be, changed.

Also, what kind of description are we looking for here that would be a required field?
- Russ

Inline image 1

**Comment by jknewson** [comment]
Maybe remove not defined checkmark option... seems odd to have that in there... IMO not defined = nothing checkmarked

**Comment by HansVraga** [comment]
@troddick Did we fix this?

**Comment by troddick** [comment]
toggle check works now. Do we want to remove 'Not Defined'?

**Comment by troddick** [comment]
Still waiting for response on question. "Remove 'Not Defined'? Felt Marie wanted this in for a specific reason.
