### ISSUE TITLE
A couple changes to the log-in screen

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#308]
- [x] remove reference to the Map Services
- [x] remove Marie's information
- [x] Add Todd Koenig's information:

> Todd Koenig, P.E.
> Office of Surface Water
> U.S. Geological Survey
> Office: 573-308-3924
> email: tkoenig@usgs.gov
- [x] Add "For new user log-in credentials, contact your Data Chief." 

![image](https://cloud.githubusercontent.com/assets/12058013/19237530/60d26962-8ecb-11e6-850e-259c8767eabf.png)

**Comment by troddick** [comment]
Am I replacing 'If you have questions about STN or need assistance, please contact:' 
with 'For new user log-in credentials, contact your Data Chief.'? Or, adding a new line under the questions one?

**Comment by HansVraga** [comment]
Above "If you have questions..." add the Data Chief message - so like this:

> For new user log-in credentials, contact your Data Chief.
> If you have questions about STN or need assistance, please contact:
