### ISSUE TITLE
Issues when entering DMS instead of Lat Long decimal values

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#312]
A user discovered a bug when trying to leave off the "Seconds" part of Degrees/Minutes - the result was "NaN" was filled in to the field value. We should take another look at that entry option to try to avoid "NaN". 

> Hans,
> 
> I have re-entered the two deleted sites and it appears the NaN is not there anymore. My GPS only provided degrees and minutes so we left the seconds box blank the only way we could keep NaN off is to fill in a zero in the seconds Box.
> 
> Thanks,
> Chris

**Comment by HansVraga** [comment]
I'd be OK with either an alert instructing the user to fill out the DMS completely, but open to other ideas.

**Comment by HansVraga** [comment]
Suggestion from Todd:

> Chris,
> In the future, if you GPS only provides degrees and decimal minutes, just put in the digits left of the decimal into the minutes box, and then multiply the decimal part by 60 and put that in the seconds box.  For example, if the output was 34 degrees 17.46 minutes, then 17 goes in the minutes box and 27.6 goes in the seconds box (0.46 x 60 = 27.6).
> 
> Hans, we might consider adding this as a feature to the minutes box.  If there is a decimal portion in the minutes box, have it automatically do the math and populate the seconds box on-the-fly for the user.
> 
> -Todd

**Comment by HansVraga** [comment]
It's also possible to paste in values to get around the field validation in STNWeb

**Comment by HansVraga** [comment]
@troddick didn't we finish this?

**Comment by troddick** [comment]
fixed lat/long pasting in incorrect NaN string, all three DMS fields are required to toggle back to Dec Deg for conversion and to save the site
