### ISSUE TITLE
add username column to the users view

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#313]
> Another enhancement request:
> 
> It would be good to see usernames as one of the columns in the Member list under Settings.  I am running into users who were setup as "username@usgs.gov", probably by data chiefs who forgot our protocol of just using the username.  But if they saw the usernames in the list, it might remind them on their way in.
> 
> -Todd

**Comment by troddick** [comment]
Done in stntest

**Comment by troddick** [comment]
done in production
