### ISSUE TITLE
Add Bulk File Download to STNWeb

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#318]
Update the "Event" modal in STNWeb to allow for bulk download of event files. This is going in STNWeb rather than the data download section because of the possibility of PII.

Two main tasks:
- [x] update the Event modal to have seperate "View" and "edit" displays, with an "Edit" button to switch between them
- [x] Add an accordion at the bottom with the bulk file download 2 tier filters of 1. Object (Site, Dataum, HWM, Sensor) then 2. File Type (dependent on object selected). This should only be visible to Admins.

**Comment by troddick** [comment]
Only event-based Object (tier 1) : HWM files or Sensor Files
- added toastr notification that says the zip file is downloading. This will stay up until the file response is back.
- check for files count before proceeding with saveAs dialog (if zero - show modal stating no files for their query)
- check for 'internal server error' (too large) show modal suggesting user to narrow their search.
