### ISSUE TITLE
Duplicate peak in STN Web

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#319]
At site FLTAY03360:
![image](https://cloud.githubusercontent.com/assets/12058013/19526224/c5109f8e-95f1-11e6-994e-548ef218334d.png)

FEV only displays one (probably assumed one peak per event)
![image](https://cloud.githubusercontent.com/assets/12058013/19526200/ac0a1cfe-95f1-11e6-8c63-8cc84a2dc9b0.png)

**Comment by HansVraga** [comment]
We should:
- [ ] Remove the duplicate (ensuring FEV still has one displayed)
- [ ] Investigate if there are others that need to be fixed.

**Comment by BlakeDraper** [comment]
Yeah for the record I purposefully only show one peak in FEV -there should only be one, since its a peak.

**Comment by troddick** [comment]
need to add distinct to Peak_View request. Same peak is being returned twice.
https://stn.wim.usgs.gov/STNServices/Sites/3360/PeakSummaryView.json

**Comment by troddick** [comment]
Fixed.
