### ISSUE TITLE
Photo Caption mismatch

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#320]
Hans,

I noticed while cross checking between STN entry and the FEV that there is a discrepancy with the dates listed in the captions on the FEV side.

On the STN entry side for photos, it gives a preview caption that lists the date the photograph was taken.  See screen capture.

STN  HWM file entry
![image 4](https://cloud.githubusercontent.com/assets/12058013/19533438/c5906b08-960d-11e6-931a-1dac43819501.png)

However, when viewing the caption from the FEV, the date for photograph caption is not the date the photograph was taken, but rather the date it was entered into STN. See screen capture:

FEV view:
![image 5](https://cloud.githubusercontent.com/assets/12058013/19533431/b7cc26e2-960d-11e6-853d-9b1df56c4c48.png)

Is this a bug?

Thanks,
## Sara

---

Sara Hammermeister
shammer@usgs.gov

**Comment by HansVraga** [comment]
Make FEV match STNWeb - show the date the photo was taken

**Comment by troddick** [comment]
Fixed (date and overlapping images)
