### ISSUE TITLE
Keep Filename on download

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#321]
See message from Harry. I had this happen when I tested too - just says "item".

>  If I click on a "_.nc" file, it will download, but it's named something like "Item (8)" instead of retaining the "_.nc" name.  If it were to stay as a "*.nc" file, many users would recognize it as a netCDF file and would know how to use it and/or view it. Can we retain the name seen in the link on the FEV?

**Comment by troddick** [comment]
I believe this has been fixed. When user downloads file by clicking file name in file description modal, the file downloads with the filename.extension. 
Please reopen if this is not resolved.
