### ISSUE TITLE
Add Save button to bottom of edit screens

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#327]
> Good morning Hans,
> 
> This may be a picky observation, but when editing any Datum, HWM, etc.... the save button is at the top of the page, which if you are reading through all the data or adding, you're going to always be scrolling to the bottom and going back to the top seems counter intuitive.  It may be more efficient to move the Save and Cancel buttons to the bottom.  It may not save much time, but could would be more intutive.  I noticed the save button is at the bottom when editing the site information.
> 
> Thanks,
> Sara

![image 6](https://cloud.githubusercontent.com/assets/12058013/19645745/48280bb6-99c4-11e6-8983-0a1af90b133f.png)

**Comment by troddick** [comment]
Live in stntest

**Comment by tkoenigusgs** [comment]
Looks good.
