### ISSUE TITLE
Change Site File Upload

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#328]
Update the file upload "+" functionality to instead work like other objects within STNWeb - only allow uploads from an accordion at the bottom of the "Edit Site" modal.

**Comment by tkoenigusgs** [comment]
looks good.  My only remaining suggestion would be to add a flyover help to the File accordion of the "edit site" modal as follows:
"For general site files only.  Please add event-specific files (e.g. HWM photos, field sheets, sensor data files, etc.) by editing the Datum, Sensor, HWM, or Peak sections within this site and uploading files from there ."

**Comment by troddick** [comment]
Sounds good. I removed 2 things: "Datum" and "Peak" as .datum location files are not event specific, and one cannot upload files to a peak.
"For general site files only. Please add event-specific files (e.g. HWM photos, field sheets, sensor data files, etc.) by editing the Sensor or HWM sections within this site and uploading files from there."
Only HWMs and Sensors carry event-specific files.
