### ISSUE TITLE
event create/edit help text wording for start/end dates

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#334]
Need wording to add to the event create and edit pages to notify admin how to handle populating the start and end dates of an event.

**Comment by troddick** [comment]
**The Start Date of an Event is when water starts rising. It does not include when equipment is pre-deployed to the study area even though flooding is imminent.

The End Date is when the water recedes to near-normal levels in the entire study area. Data collection will likely continue past this date. When creating an Event, estimate the end date so that the NWSI graphs in FEV operate correctly. The Start and End date range is used once the end date is passed. Make a best guess and come back to finalize it. 

For example, if we are documenting a spring melt in the Mississippi Basin, the Start Date could be sometime in March for the upper tributaries and the Event would remain open until the flood crest had attenuated in the system, likely months after the upper tributaries return to low-flow conditions. In the case of estimated historical events, choose the first date of the month around when the flood may have started and end the flood at least 30 days later if no other information is available. Cite your sources in the comments box for all dates when the flooding occurs outside of the instrumented record. 

Events may not start and end on the same day. Short floods will have a minimum duration of two consecutive days for graphing and filtering ease. 

The Event Dates shall never be determined by anything other than the hydrologic record (i.e. DON'T use funding agreements as Start and End dates)

**Comment by troddick** [comment]
"Event Status" to  "Data Collection Status"

**Comment by troddick** [comment]
Is this the exact wording to be added to the event create and edit pages?

**Comment by troddick** [comment]
![image](https://cloud.githubusercontent.com/assets/1580076/22792353/1227adda-eeb2-11e6-93b9-32078305d510.png)

Added to the event start date only. Thoughts?

**Comment by tkoenigusgs** [comment]
I would go ahead and duplicate it for the end date as well.
