### ISSUE TITLE
Change title of Event Status field to "Data Collection Status"

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#340]
(End of an email thread discussing this change)
>I agree that 'Data Collection Status' is most accurate term if the definition of that field is the status of USGS data collection efforts. I think its fine to leave the DB field name in the event table as 'status', so this change is more a superficial one for the web clients, both STNWeb, FEV, and STN Data Portal. Tonia and I will make updates accordingly to the UI of those apps so they display the event status as Data Collection Status.

**Comment by troddick** [comment]
stnweb has this update in stntest currently. (soon to be in production)

**Comment by tkoenigusgs** [comment]
Looks good.
