### ISSUE TITLE
zip file download of event files

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#349]
Add state, county, toDate-fromDate filters (stnservices and stnweb)
Look into chunking or check to see how large the zip file is before doing it. ping s3 bucket to see size.
http://stackoverflow.com/questions/3910071/check-file-size-on-s3-without-downloading

**Comment by troddick** [comment]
additional filters added.
haven't looked into chunking or pinging the s3 bucket yet.

**Comment by tkoenigusgs** [comment]
Seems much-improved!
