### ISSUE TITLE
tooltip on datum location files

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#350]
Datum location files section of datum location modal:
add (?) that says 'Files uploaded to datum location are not tied to an event. To associate a file with an event, please upload through a sensor or hwm instead of here'

**Comment by troddick** [comment]
done in stntest.

**Comment by tkoenigusgs** [comment]
I couldn't find the (?) in stntest.  Maybe I'm looking in the wrong place?

**Comment by troddick** [comment]
@tkoenigusgs  Go to a Site Dashboard that has a Datum Location, for example:
http://stntest.wim.usgs.gov/STNWeb/#/Site/3289/SiteDashboard

Click on a Datum location from the Datum Location accordion list. Towards the bottom of the modal is the Datum Location Files. The (?) is to the right in the header for the files accordion.
![image](https://cloud.githubusercontent.com/assets/1580076/23948423/e993a428-0950-11e7-9a9b-6eb135e80e3c.png)

**Comment by tkoenigusgs** [comment]
Looks good to me.  Thanks!
