### ISSUE TITLE
Peaks in Historic HWM interface

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#355]
Add the ability for Historic HWM uploaders to add peak infromation in the same manner they attach files to the HWM. Show an "ad peak" button for each HWM that opens the same "Peak" modal that you can access from a site page. Once a Peak is added, change the button for all HWMs part of that site-event to "edit peak"

**Comment by troddick** [comment]
Updated task issue:
Historic HWM can only upload Approved hwms. Must provide a file (link or actual file) before able to paste/ add to the table.
