### ISSUE TITLE
stntest obnoxious banner

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#360]
Letting users know they are in the test server and not updating real production data.

**Comment by HansVraga** [comment]
@troddick I see we're partway there - but the orange does not tell the user "TEST" - I think our users could ignore the color as some sort of style change and carry one thinking it's prod.

**Comment by troddick** [comment]
Better?
![image](https://cloud.githubusercontent.com/assets/1580076/24116837/f80ccdc6-0d75-11e7-92f2-fa2161eeec07.png)
