### ISSUE TITLE
sensor script integration

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#382]
script integration for retrieved sensors. 
Data file uploaded on a pressure transducer of 
Sensor Brand types: Measurements Speciality, Hobo, or Level Troll
on a Water Level or Wave Height Deployment Type

After Data File Uploads, show 'Process script' button (maybe provide tooltip info?). Clicking button shows section with list of Air Pressure (Barometric) Sensors for them to choose one. List will include distance from this site and good start/good end dates to help narrow chosen sensor. The Data file just uploaded and sensor that it's attached to will be used as Sea Pressure sensor/data file.
User must also check box "Was instrument sampled at 4 Hz" and pass as boolean in post request.
Post will have  
   - 2 sensors (Air and Sea) 
   - 1 data file (the one just uploaded) 
   - boolean 4Hz value
   - member logged in?
   - not sure what else is needed

**Comment by HansVraga** [comment]
Done. Other issues are tracking follow-up work.
