### ISSUE TITLE
Add Message to Bulk HWM Adjustment page

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#386]
Users have discovered that simultaneous edits via the Bulk HWM adjustment page can lead to unexpected (to them) results. Lets add a warning for them:
Add the following bullet item:
"WARNING - simultaneous edits of a HWM through this interface may lead to unexpected results."
here:
![image](https://user-images.githubusercontent.com/12058013/29784475-10b3cbb8-8bf2-11e7-8ca1-abc1a65b81ac.png)

**Comment by troddick** [comment]
Done
