### ISSUE TITLE
Update Photo Description ? text

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#391]
Append the following onto the description text (circled in screenshot):
"If a person or people appear in photo include name(s). If non-USGS personnel, ensure consent to publish name in caption is given."

![image](https://user-images.githubusercontent.com/12058013/30070220-c74ad224-9230-11e7-8996-3e09789f2592.png)

**Comment by troddick** [comment]
Making the assumption that this is an update to all places where a photo file can be uploaded and not just in the sensor file upload section.

**Comment by HansVraga** [comment]
That assumption is correct!

**Comment by troddick** [comment]
done
