### ISSUE TITLE
Reload site after site edit

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#393]
This might actually be a known bug with a new example of how it manifests itself.  (Skip past the numbered list if you want the short cut.)  Kristine Blickenstaff pointed out the following scenario which will likely need fixing in the next version of STN:

User creates a site with the wrong lat/lon and saves it.  ( I did an example in the test environment where the lat was 38.00666 and long was -92.00666).
User edits the site lat/lon to the correct value.  (in my test, I corrected them to 38, -92)
User adds an HWM to the corrected site.
System defaults the previous site lat/lon into the HWM lat/long until the user enters actual HWM lat/long.
User enters lat/long that is close to the new site lat/long (I chose 38, -92 in test - right on top of new site location).
System warns user that they are creating an HWM that is more than 232 feet from the site location, which isn't true.  The new HWM is very close to the new site location.
User proceeds with HWM creation and returns to Site Dashboard.
At the Site Dashboard, user presses F5 to refresh the Site.
User tries adding a second HWM.
The second HWM editor shows the correct default locations, so no further problems are experienced.
So it really just comes down to the fact that the site does not re-load into the browser after an edit is made to the site.  STN needs to automatically refresh the Site Dashboard for current site anytime an edit is made to the site.  

I'm pretty sure this would solve additional problems we are seeing in the field when sites are edited and then further work is done in the site (very common).

-Todd

**Comment by troddick** [comment]
fixed.
