### ISSUE TITLE
snapshot of what the stn production database looked like on Wed (9/6/17) morning

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#394]
A sensor (instrument table, instrument_id: 7679) was accidentally updated. Only this row in the db needs to be back to what it was. I can do this manually, if I can get access to the db as it looked yesterday.

**Comment by aaronstephenson** [comment]
Done @troddick 
stn-sept6.ck2zppz9pgsw.us-east-1.rds.amazonaws.com
Same creds as the main STN database.

Let me know when you're done so I can terminate this.

**Comment by troddick** [comment]
I'm done with it. Thank you!!
