### ISSUE TITLE
site dashboard image files carousel

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#396]
Image files showing in carousel in the Files accordion are showing all files for the site, irregardless of event.

**Comment by troddick** [comment]
Need to add logic in fileCtrl.js (line 23-42) to add fileEvent before setting SiteFiles. Then look for value in $cookies.get('SessionEventID') and match to fileEvent value.

**Comment by lprivette** [comment]
not worth the effort to fix in current client. May apply to future refactor.
