### ISSUE TITLE
Most recent snapshot of production database as new stntest

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#397]
Can we have the most recent snapshot of the production database turned in to the new stntest database? 
If possible, can it have the same name as the test database, so then I won't have to update anything in stnservices. 
Please let me know right when this is done so that I can go in and add a field to one of the tables (there is one 1 small difference between prod and testing db, needed for stntest's stnweb and stnservices to work).

**Comment by aaronstephenson** [comment]
Done.
