### ISSUE TITLE
Add Text to PUblic STNWeb pages

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#403]
From Todd:
>Could we just do a quick header modification for the Peak Summaries section of a Sensor Data Page to help reduce confusion related to this issue?  Robert and I are thinking something similar to the red line inserted below (of course, not red in the actual edit):
![image](https://user-images.githubusercontent.com/12058013/32176974-0b69b032-bd57-11e7-972d-dd23d79534ec.png)

**Comment by troddick** [comment]
Since this app is so small, I'm going to also refactor it to angular. Shouldn't take too long (maybe few hours tops).
We should move this issue to the STNPublicInfo repo though.
