### ISSUE TITLE
Create a REPORTING dashboard 

### ISSUE THREAD

**Issue by tkoenigusgs** [USGS-WiM/STNWeb#411]
Field managers spend a lot of time reporting daily stats to executives on daily calls for things like HWM counts, sensor counts, etc.  These get passed up the line, wasting a lot of time at each step.  A dashboard with ~some or~ all of the required elements would streamline the data entry and make the results available to any ~internal~ user with access.  ~Options from easiest to hardest:~

~**Easiest**: Create endpoints for counts of data we already have in STN (this would just be a repeat of STNServices issue #127 below)~

~**Harder**: Use the existing REPORTING section of STNweb to show the counts of HWMs and Sensors, subtotaled by State and status:~
  ~**_Sensors: (deployed / recovered / uploaded / approved)~
  ~HWMs:(flagged / surveyed / unapproved / approved)._**~
~STN would store these values and allow the Manager to view/edit previous days counts.~  It would allow users to download this data in csv format for inclusion in spreadsheets and reports.  A special endpoint would be useful for downloading the csv by event.

~**Hardest**: Allow additional non-STN data to be manually entered by Managers into the REPORTING section, including:~
  ~**_special flood measurements,~ 
  ~special QW measurements,~ 
  ~planned/completed indirect measurements,~ 
  ~gages down/damaged/destroyed/repaired,~ 
  ~Peaks of Record,~ 
  ~rating extensions needed/created._**~  
~Each of these items would have 3 fields for "yesterday", "today", and "tomorrow", where the most current entry always updates the previous one.  Some of the items above might be pulled automatically from NWIS or WaterWatch through web services.~

**Comment by tkoenigusgs** [comment]
After 10/4/18 meeting, we decided it would be best to make the STN reporting feature part of FEV where everyone could access it, and we would only report stats found in our own data.  (I.e. we will not collect other data like personnel, gages down, rating extensions, etc.).  Here's a list of Counts that we need to display _for the event_:


High Water Marks  
  **all HWMs**  (FilteredHWMs.json?Event=<EventID>)
      **surveyed HWMs**  (FilteredHWMs.json?Event=<EventID>&SurveyComplete=True)
      **unsurveyed HWMs** (FilteredHWMs.json?Event=<EventID>&SurveyComplete=False)
      **approved HWMs** (HWMs.json?Event=<EventID>&IsApproved=True)
      **unapproved HWMs** (HWMs.json?Event=<EventID>&IsApproved=False)
  **HWM sites** (count of all unique sites that have at least 1 HWM for the event)

Sensors
  **RDGs** (FilteredInstruments.json?Event=<EventID>&SensorType=5)
      **Deployed RDGs** (FilteredInstruments.json?Event=<EventID>&SensorType=5&CurrentStatus=1)
      **Retrieved RDGs** (FilteredInstruments.json?Event=<EventID>&SensorType=5&CurrentStatus=2)
      **Lost RDGs** (FilteredInstruments.json?Event=<EventID>&SensorType=5&CurrentStatus=3)
   **SPTs** (FilteredInstruments.json?Event=<EventID>&SensorType=1&DeploymentType=1,2,3)
      **Barometers** (FilteredInstruments.json?Event=<EventID>&SensorType=1&DeploymentType=3)
      **Water level** (FilteredInstruments.json?Event=<EventID>&SensorType=1&DeploymentType=1)
      **Wave level** (FilteredInstruments.json?Event=<EventID>&SensorType=1&DeploymentType=2)
      **Deployed Water+Wave** (FilteredInstruments.json?Event=<EventID>&SensorType=1&CurrentStatus=1&DeploymentType=1,2)
      **Retrieved Water+Wave** (FilteredInstruments.json?Event=<EventID>&SensorType=1&CurrentStatus=2&DeploymentType=1,2)
      **Lost SPTs** (FilteredInstruments.json?Event=<EventID>&SensorType=1&CurrentStatus=3)
   **Sites** (number of sites containing at least one sensor of any sensor type for the event)

Peaks
      **Peaks** (FilteredPeaks.json?Event=<EventID>)
      **Sites** (number of sites with at least 1 entered peak for the event)

In addition, the stats page needs to break down all of the above by state so that the first column contains the total numbers above, while the remaining columns have the same counts for each state that is currently part of the event.

Finally, we need to create an endpoint that gives the same results so that these stats can be ingested into other reporting applications.

**Comment by HansVraga** [comment]
Issue moved to new repo, see reference above.
