### ISSUE TITLE
test script running against provided files

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#417]
failing for Ryan in stntest

site/3089 instrument - Pressure transducer, csv file 1028526.csv
site/3089 instrument - Baro, csv file 1028521.csv

**Comment by troddick** [comment]
Run Storm: 
/DataFiles/RunStormScript?SeaDataFileID=6066&AirDataFileID=6068&Hertz=false&Username=fradmin

Run Air:
/DataFiles/RunAirScript?AirDataFileID=6068&Username=fradmin

**Comment by lprivette** [comment]
OBE
