### ISSUE TITLE
Remove NAD27 & NGVd29 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#418]
Request from Cooperator:

> I've talked to my local GNSS and surveying expert and I'm making the call to go ahead and selectively remove NAD27 and NGVD29 if possible.  (If not, skip to the end...)
> 
> Specifically:
> Remove NAD27 horizontal datum option from:
> All Site entry modals (including quick entry modals)
> HWM entry modals (including quick entry modals)
> Keep NAD27 horizontal datums for:
> Datum Location modal
> 
> Remove NGVD29 vertical datum option from:
> HWM entry modals (including quick entry modals)
> All deploy sensor and retrieve sensor modals
> Keep NGVD29 vertical datum option for:
> Datum Location modal
> Peaks modal
> Any values currently in the database using either of these can and should remain as-is.  

>If it turns out that we cannot selectively remove NAD27 and NGVD29 options from some modals and leave them in others, then my preference is to remove them from all modals, and the data in the database can remain (hopefully without violating any constraints).

**Comment by troddick** [comment]
The options will stay in the hdatum and vdatum tables, but will be removed from the requested locations after a check is done to see if the entity (site/hwm/sensor) has the hdatum/vdatum in question. If it does, then it will remain in the options, but be disabled for selection during edit. It will be removed from the options list in the create page of the requested locations.

**Comment by lprivette** [comment]
- [x] leave options in the hdatums vdatum tables
- [x] Remove NAD27 horizontal datum option from:
     - [x] All Site entry modals (including quick entry modals)
     - [x] HWM entry modals (including quick entry modals)
     - [x] Keep NAD27 horizontal datums for Datum Location modal
- [x] Remove NGVD29 vertical datum option from:
     - [x] HWM entry modals (including quick entry modals)
     - [ ] All deploy sensor and retrieve sensor modals
     - [x] Keep NGVD29 vertical datum option for Datum Location modal & Peaks modal
- [ ] add check to see if entity (site/hwm/sensor) has the hdatum/vdatum in question. If it does, leave it in the options, but disabled it for selection during display.

**Comment by lprivette** [comment]
Done aside from the check.

Having trouble getting ng-options to observe my ng-disabled for the existing records that have NAD27 or NGVD29.

**Comment by lprivette** [comment]
This one gets a little complicated with the deployed/retrieved sensors and the datum locations added via the tapedown. If NGVD29 is selected in the datum location, then it will be there when click on a deployed or retrieved sensor. If a datum location is selected and the vertical datum is not NGVD29, then NGVD29 will not be list as an option in the tapedown. Need to check if this is the desired behavior.

Also have not found a workaround for the ng-disabled on the records that have NAD27 or NGVD29. At the moment that option remains if it was selected prior to this fix. If they select another datum and save the NAD27 or NGVD29 options will not be listed from then on.

In Test.

**Comment by tkoenigusgs** [comment]
This looks to be about as good as we can get it.  At some point, it would be nice to display all points correctly on the STN and FEV maps by converting them automatically from their stated datum using services found here:  https://www.ngs.noaa.gov/web_services/ncat/index.shtml.  This would be similar to what we do with time, where we store everything in UTC.  Maybe we could add a field to the tables that hold sensor, site, and hwm location data that stores the locations as the most modern datum, so that all points truly to plot correctly.

**Comment by lprivette** [comment]
in prod

**Comment by lprivette** [comment]
reverting this change due to users entering in historical data.

Issue in test for review.

**Comment by lprivette** [comment]
issue reverted in production.
