### ISSUE TITLE
daylight savings/ utc script running discrepancy 

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#419]
Ryan Hollins: "The only things I noticed are some slight differences in the final values and times.  I'm assuming this is related to the script.  I attached pictures from the same data processed from Irma, which we all assumed to be correct at the time as we were using the latest script.  I included Greg so that he can give thoughts.  The newer script (assuming the one embedded in STN is the latest) puts the unfiltered peak 0.12' higher and 1 hour later than the script we were using during Irma.  Interestingly the unfiltered peak from the test version of STN gives a value of 4.99', which lines up very well with a pretty good HWM we obtained at that site surveyed to 5.01'. Greg, the same data was used and the same elevations were used for both instances. "
![image](https://user-images.githubusercontent.com/1580076/36331997-dd54ce90-1335-11e8-8f3e-1eee088e1f13.png)
![image](https://user-images.githubusercontent.com/1580076/36332002-e701b16a-1335-11e8-9009-e43155d7259a.png)

Suggested attempt at a fix is to add a checkbox near the Run Script button asking user if data was recorded in daylight savings? This would require an update to the stnservices to accept this boolean parameter and adjust what parameters are sent to run the scripts. 

Ryan does not think it is the daylight savings thing. He understands that data is recorded in UTC. He was going to let me know when he wanted to test this theory, and I was going to update the services to pass 'true' for daylight savings, and he would rerun and see if it fixed it.

**Comment by troddick** [comment]
- [x] add a checkbox to the sensor data file (water level/wave height - retrieved ) in the area that lists all baro sensors to choose from after they click "Run Storm Script"

- [x]  add a checkbox to the sensor data file (Pressure Transducer -retrieved) in the area that will show once they click 'Process Air Data File'

- [x] update the controller function to pass this true/false value along 

 checkbox should ask: 'Check this box if data was recorded in daylight savings?'

- [x]  update the factory resource request to accept the new parameter

**Comment by troddick** [comment]
live in stntest

**Comment by lprivette** [comment]
On the backburner until we can discuss with Ryan.

Todd - "I vote we put this issue on the back-burner until I get a chance to talk to Ryan and get more details.  He's in Puerto Rico doing field work at the moment, but I'll setup some time to talk with him when he gets back."

**Comment by lprivette** [comment]
Does not apply.
