### ISSUE TITLE
Create STN EC2 instance

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/STNWeb#422]
STN production is 💩 'ing out, Plan is to migrate STN to its own, properly sized instance and off of Toad, to help isolate the issue for further diagnostics and trouble shooting.

**Comment by aaronstephenson** [comment]
We will need GTRI to create a new managed instance for us. In the meantime, we decided to create our own pseudo-production instance in the WIM sandbox account, and direct all STN production traffic to that, until the new managed instance is ready.

**Comment by aaronstephenson** [comment]
Pseudo-prod is ready.

**Comment by HansVraga** [comment]
@jknewson @lprivette Is there more work here, or should we close this issue?

**Comment by lprivette** [comment]
If there is a separate ticket for the migration to the GTRI Instance, then yes it can be closed. If not then maybe leave it open until that is complete?

**Comment by lprivette** [comment]
Closing this because STN-Pseudo is working and stn-ding by in case current prod 💩's again. 

We are going to wait until the Services are refactored before submitting the ticket to GTRI for an instance in the WMA sub account
