### ISSUE TITLE
Create Sites STN Data Dictionary Page

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#424]
From Todd:
>OK... I've created three of the four data dictionaries (the three that Dr. Arctur was looking for).  Would Lauren be able to create the fourth one (Sites)?  Might be a good exercise for getting to know the data and getting to know Confluence (or maybe that's all old hat for her!).

STN Data Dictionary Confluence Pages: https://my.usgs.gov/confluence/display/WSN/STN+Data+Dictionary+-+Top+Level

**Comment by lprivette** [comment]
updated sites here: https://my.usgs.gov/confluence/display/WSN/STN+Data+Dictionary+-+Sites

Wasn't sure what to put for `objective_points`

**Comment by lprivette** [comment]
Updated following guidance ☝️ https://my.usgs.gov/confluence/display/WSN/STN+Data+Dictionary+-+Sites
