### ISSUE TITLE
STNTest server not shutting down on weekends or nightly

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNWeb#438]
Was STNTest removed from the nightly shutdown list on S3? I'm guessing that txt file is in the `wim-lambda` folder, but I don't have access to view or edit.

I was on Standby this weekend to start it up for Todd on Sunday night, but it was on all weekend and never shutdown at night. I don't think it's supposed to be on during the weekends as well.

**Comment by aaronstephenson** [comment]
Yes, it was removed from the nightly shutdown list on May 21 per your request. No one ever requested that it be placed back on to the list.

![capture](https://user-images.githubusercontent.com/8713712/44687484-f7e85100-aa16-11e8-9b2a-df5a8dbda539.png)

So do you want it back on the nightly shutdown list? It's still on the daily startup list, was never removed from that one.

**Comment by HansVraga** [comment]
Yes, let's add it back to the list.

**Comment by aaronstephenson** [comment]
Done.
