### ISSUE TITLE
Replace jQuery-dependent page loading indication logic with Angular approach

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/STNWeb#44]
I noticed in many of the controllers reliance on `$(".page-loading").removeClass("hidden");` to hide a page loading div using jQuery. I agree with @jknewson's philosophy on this, that Angular can and should supercede jQuery. We should find a more Angular-y way to show and hide page loading indicators. I am using a package called angular-busy on the map element, but that may not be the best fit. I will look into this, unless @troddick beats me to it.

**Comment by troddick** [comment]
I can take care of this. I found a directive that listens for $routeChangeStart and can show/hide an element the angular way.

**Comment by troddick** [comment]
ended up using $stateChangeStart and $stateChangeSuccess to set $rootScope.stateIsLoading boolean property as well as setting this property in controllers where onClick function requires the loading to show while processing. The index has an ng-class assigned that depends on the boolean.
