### ISSUE TITLE
Potential issue with DST and peaks

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#441]
>I've got a new (but old?) issue being reported.  In a nutshell, when the users is entering a Peak, and they type in the Time of the peak, and they select EST (which should be UTC-5 hours), it is somehow being stored as UTC-4 hours.  You can prove this by entering a test time as EST, then saving it, then coming back and looking at the time in the default UTC format.  I haven't tested to see whether the other time zones listed are accurate or not.

**Comment by lprivette** [comment]
Need to test date in each on time_fix test site:

- Peaks
    - Edit peaks
- New Sensor
- Edit deployed sensor
    - Add data file to deployed sensor
     - Edit data file
    - Add nwis connection
    - Edit nwis connection
- Edit Retrieved sensor
    - Add data file to retrieved sensor
     - Edit data file
    - Add nwis connection (RDG)
    - Edit nwis connection (RDG)

**Comment by lprivette** [comment]
in prod
