### ISSUE TITLE
Deploy back up of STN prod from before 12/12

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNWeb#445]
We did a bulk delete of all proposed sensors and need to check a previous version of the DB to verify the status of an instrument. We need to poke around the database to investigate anomalies being reported in current prod (after deletion of sensors).

Ping me for questions.

**Comment by lprivette** [comment]
Dan deployed the snapshot.

**Comment by aaronstephenson** [comment]
Delete the backup that you created when deleting the restored DB. There's no need for a backup of a backup.
