### ISSUE TITLE
Make Deployment Type field required

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#466]
Deployment Type field should be required for sensor deployments of types: Pressure Transducer, Meteorological Station, and Thermometer; but not for other sensor types.

**Comment by HansVraga** [comment]
@lprivette is it possible to make it required for some but not others?

**Comment by lprivette** [comment]
Probably --I haven't done this with angularJS yet, but I'd be surprised if we couldn't do this. I'd have to look into it (also I am out of hours). What is the priority on this?

**Comment by lprivette** [comment]
To clarify this would just be requiring it on the client-side. If some one wanted to submit it via a rest client there would be no requirement.

**Comment by lprivette** [comment]
duplicate of https://github.com/USGS-WiM/STNWeb/issues/492
