### ISSUE TITLE
Unable to connect to STN RDS

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNWeb#474]
I'm trying to connect to stn prod db via Navicat.

**error**: 'connection timed out. is the server running on host stn.ck2.... and accepting tcp/ip connections on port ..."

I'm able to connect to other dbs if I'm off network, but not able to connect to any if I'm on network.

I haven't needed to connect to it for a while but if i remember correctly i have to be on network to connect to STNs prod db. I've verified the rds server is running.

Could this be a cert issue? I'm not sure what to try next here.

**Comment by aaronstephenson** [comment]
I added your home IP address to the STN RDS security group, as well as adding the USGS VPN subnets.
