### ISSUE TITLE
Turn on hourly back ups for live event

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNWeb#506]
Data being entered for Tropical Storms Marco and Laura

**Comment by aaronstephenson** [comment]
@PatrickMooreUSGS this is a good one for you. Super quick and easy. Contact me when you have 2 minutes.

**Comment by aaronstephenson** [comment]
Enabled.

**Comment by HansVraga** [comment]
@lprivette - stumbled across this issue while doing some cleanup. Data collection still active or can we dial this back yet?

**Comment by lprivette** [comment]
technically still active for Sally
