### ISSUE TITLE
Remediate Vulnerability: Outdated Javascript Library

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/STNWeb#511]
Acunetix scan reports this app is using AngularJS 1.4.7 and should be updated.

**Comment by aaronstephenson** [comment]
This is an "info" level vulnerability, so no rush to remediate. If it is too burdensome, feel free to ignore, just make a note about it here.

**Comment by lprivette** [comment]
Ok thank you Aaron. With a refactor of this application in works (https://github.com/USGS-WiM/stnweb2) I will defer this remediation for now.
