### ISSUE TITLE
STNWebTest server on WMA not shutting down with nightly shutdowns

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNWeb#513]
If I'm following the history correctly, STNWebTest ec2 instance should be on a nightly shutdown script: https://github.com/USGS-WiM/STNServices2/issues/150

**Comment by aaronstephenson** [comment]
The lambda script was failing because one of the instances listed in the text file no longer exists. I corrected the list, and will alter the script to not error out when encountering this situation in the future.
