### ISSUE TITLE
STN Calls taking 10-20 seconds to succeed

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNWeb#515]
https://stn.wim.usgs.gov/STNServices/HWMTypes.json

Usually a request like the one above is pretty instant. I'm not sure when this actually started. I just noticed it today around noon.

Hans told me that Toad was restarted over the weekend because AWS needed to migrate it to new hardware.

**Comment by lprivette** [comment]
I checked the drives on Toad and they were not full or in the red

**Comment by aaronstephenson** [comment]
There's a possibility the server restart has something to do with it, but then every service hosted there would be slower too.

I think the path forward is to identify where in the network chain the slowdown occurs. Check the DB query, check the data call in your code, then check the request in IIS.

**Comment by lprivette** [comment]
I noticed at 2pm today that STN Services calls were functioning normally. I have not made any changes to the services or Toad. 

I will check periodically over the next couple days.
