### ISSUE TITLE
I bought a new router; need IP added to STN RDS security group and USGS VPN subnets

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNWeb#516]
Sorry, won't have to request this again for a while now :) 

Should probably remove old home IP.

Who should I DM my new home IP to?

**Comment by aaronstephenson** [comment]
@lprivette you can DM me.

**Comment by aaronstephenson** [comment]
New IP address added and old ones removed.

**Comment by lprivette** [comment]
I have purchased a new router and so have a new IP 😬 DMing address to Aaron

**Comment by lprivette** [comment]
Aaron added my IP and I confirmed that I could connect to the DB
