### ISSUE TITLE
Remediate Vulnerability: Password field submitted using GET method

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/STNWeb#518]
Acunetix scan reports this app uses GET to submit passwords. Passwords must be submitted using a POST request. This is a Medium vulnerability and is a priority. The specific file reported is:

>https://stn.wim.usgs.gov/stnweb/component/logInOut/login.html

**Comment by lprivette** [comment]
Same fix we did for SIGL, isn't working in STN, naturally. code is Identical in the services. I'll have to trouble shoot after hours as Ron is trying to create a new event in stn

**Comment by lprivette** [comment]
Corrected with: https://github.com/USGS-WiM/STNServices2/releases/tag/v2.2.5 and https://github.com/USGS-WiM/STNWeb/releases/tag/v2.4.0

both deployed to production
