### ISSUE TITLE
Hitting issues with the SITE.getAll $resource factory

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/STNWeb#54]
Trying to convert to using SITE.getAll in the map controller to reduce redundancy across the app code, but the endpoint it uses seems to be unreliable right now. 

This is what I have been using to get the sites:

``` javascript
$scope.sitesPromise = $http.get('https://stntest.wim.usgs.gov/STNServices2/Events/' + evID + '/Sites.json')
                                            .then(onSiteComplete, onError);
```

The $http.get above uses this endpoint, which works: `https://stntest.wim.usgs.gov/STNServices2/Events/23/Sites.json`

whereas the SITE.getAll uses `https://stntest.wim.usgs.gov/STNServices2/Sites.json?Event=23` and either takes ages to complete or fails completely. 

I'd rather use SITE.getAll since it returns the all the site data rather than just the 4 basic fields. Any idea what is going on with that endpoint @troddick?

**Comment by troddick** [comment]
Hitting this endpoint returned 362 sites. It takes so long because it then goes and gets all events that this site was used at, as well as the Network_Names, and the most recent OP.
I don't think you want all that for the map, do you? A better query would be the GetEventSites (event/23/Sites.json). I can return a list of Sites (all fields) rather than the SitePoint that was originally set up for some reason.
[
  {
    "SITE_ID": 7094.0,
    "SITE_NO": "NYNAS07094",
    "latitude": 40.877911,
    "longitude": -73.530571,
    "Description": null,
    "County": "Nassau County",
    "State": "NY",
    "Networks": [],
    "RecentOP": null,
    "Events": [
      {
        "EVENT_ID": 23.0,
        "EVENT_NAME": "Irene",
        "EVENT_START_DATE": "2011-08-27T00:00:00",
        "EVENT_END_DATE": "2011-08-30T00:00:00",
        "EVENT_DESCRIPTION": null,
        "EVENT_TYPE_ID": 2.0,
        "EVENT_STATUS_ID": 2.0,
        "EVENT_COORDINATOR": 36.0
      },
      {
        "EVENT_ID": 24.0,
        "EVENT_NAME": "Sandy",
        "EVENT_START_DATE": "2012-10-22T00:00:00",
        "EVENT_END_DATE": "2012-10-31T00:00:00",
        "EVENT_DESCRIPTION": null,
        "EVENT_TYPE_ID": 2.0,
        "EVENT_STATUS_ID": 2.0,
        "EVENT_COORDINATOR": 36.0
      },
      {
        "EVENT_ID": 34.0,
        "EVENT_NAME": "Mock Hurricane Deployment",
        "EVENT_START_DATE": "2015-04-28T00:00:00",
        "EVENT_END_DATE": "2015-05-01T00:00:00",
        "EVENT_DESCRIPTION": "Test deployment of equipment for NY, CT and PA as part of the Sandy Supplemental testing and development. This is NOT a real event. ",
        "EVENT_TYPE_ID": 2.0,
        "EVENT_STATUS_ID": 1.0,
        "EVENT_COORDINATOR": 36.0
      }
    ]
  },.....

**Comment by troddick** [comment]
has this been resolved?

**Comment by troddick** [comment]
closing. reopen if further discussion is needed.
