### ISSUE TITLE
Lat and Lng attributes in aSite object need to be pared down

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/STNWeb#69]
Need to apply a javascript toFixed() to the aSite.LATITUDE_DD  and aSite.LONGITUDE_DD attributes. Sometimes too many figures are provided - no need to display all of them. Is causing overrun in some cases, like in the screencap below.  I would think toFixed(4) would be good. 

I am only assigning you @troddick because I'm not sure exactly where in the various logic pieces it is most appropriate to put it.

![latlngoverrun](https://cloud.githubusercontent.com/assets/6978380/13760219/014fd10c-ea00-11e5-8330-4449b2c4da7d.PNG)

**Comment by troddick** [comment]
I can take care of this. I'm handling this same issue in Site create. I have been doing toFixed(6). 
I'll take care of this tomorrow.

**Comment by troddick** [comment]
Done
