### ISSUE TITLE
map buttons appearing 'on top' of loading... screen

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNWeb#78]
When on the map tab and the loading div shows (typing site ID into Site Search box - gets site and takes user to site dashboard) before leaving the page, the map's zoom in/out buttons and layers button appears on top of the semi-transparent loading screen that covers the whole page.
![loading](https://cloud.githubusercontent.com/assets/1580076/13855130/e8710a22-ec3c-11e5-9eb4-da02e428f784.png)

**Comment by BlakeDraper** [comment]
I am thinking we need a better application-wide solution for the loading screen stuff. I had implemented this [angular-busy](https://github.com/cgross/angular-busy) library to the map itself at an early point, but you attach this to a promise and that promise became abstracted when I switched to the SITE service. We should figure a way to implement this or something like it. More targeted loading overlays would be handy, esp. on the map page.

**Comment by BlakeDraper** [comment]
addressed with PR #173
