### ISSUE TITLE
Add Legend to main Map Tab

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNWeb#93]

**Comment by BlakeDraper** [comment]
ArcGIS server does not allow you to request the legend JSON for single layers, which is a huge bummer. Will work through on a case-by-case basis, but short of taking a lot of time for custom legend parsing, for first release may end up showing some extraneous legend elements for certain services. I custom legend can be requested, but that requires enabling the "Supports Dynamic Layers" option on the server, which we have no control over for these third-party maintained services. Tracking availability and legend notes [here. ](https://docs.google.com/spreadsheets/d/1JnnDT8O0Yg8ZrkjdZZeK5H09YgHxBTCUbZexeDb4YbI/edit#gid=0)

**Comment by BlakeDraper** [comment]
I think I know what I have to do.

**Comment by BlakeDraper** [comment]
Implemented wimLegend from wim_angular
